<div>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:center; line-height:22pt; background-color:#ffffff;"><strong><span style="font-family:'Segoe UI'; font-size:22pt;">PRIVACY POLICY</span></strong></p>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:21pt; background-color:#ffffff;"><strong><span style="font-family:'Segoe UI'; font-size:14pt;">UGANDA COOPERATIVE SAVINGS AND CREDIT UNION (UCSCU)</span></strong></p>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:21pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">Your privacy is important to us. This privacy policy explains what personal data we collect from you and how we use it. It also explains how our website uses cookies. At certain times, we may change or modify our policy at our own discretion, adding or removing information to reflect current practices &ndash; in other words, giving you the most up-to-date information. When this occurs, we will update this policy with the most recent revision date. We may also retain data when required to comply with legal obligations, enforce agreements or resolve ongoing disputes. Such data will be deleted when no longer required and such incidents have been resolved.</span></p>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:normal; font-size:18pt; background-color:#ffffff;"><span style="font-family:'Segoe UI';">Who is responsible for processing your personal data?</span></p>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:21pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">UCSCU is the controller of your personal data. Our registered office is:</span></p>
    <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; line-height:normal; font-size:12pt; background-color:#ffffff;"><span style="font-family:'Segoe UI';">10Kms Bombo Road, Plot 239, Maganjo-Wakiso District</span></p>
    <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; line-height:normal; font-size:12pt; background-color:#ffffff;"><span style="font-family:'Segoe UI';">P.O. Box: 6203, Kampala-Uganda</span></p>
    <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; line-height:normal; font-size:12pt; background-color:#ffffff;"><span style="font-family:'Segoe UI';">Tel: +256 414 233 601</span></p>
    <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; line-height:normal; font-size:12pt; background-color:#ffffff;"><span style="font-family:'Segoe UI';">info@ucscu.coop</span></p>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:21pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">This is registered with the Registrar of Cooperatives at the Cooperatives Department, Ministry of Trade, Industry and Cooperatives.</span></p>
    <ul type="disc" style="margin:0pt; padding-left:0pt;">
        <li style="margin-top:14pt; margin-left:27.6pt; text-align:justify; line-height:21pt; padding-left:8.4pt; font-family:serif; font-size:10pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">We are registered under the provisions of section 5 of the Co-operative Sections ACT, 1970. Certificate Number is 2725.</span></li>
        <li style="margin-left:27.6pt; margin-bottom:14pt; text-align:justify; line-height:21pt; padding-left:8.4pt; font-family:serif; font-size:10pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">Our Taxpayer Identification Number (ID for taxpaying purposes) is 1000165626</span></li>
    </ul>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:normal; font-size:18pt; background-color:#ffffff;"><span style="font-family:'Segoe UI';">How, when, and why do we collect your Personal Data, and for how long do we store it?</span></p>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:21pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">We only store your data via request, when legal consent has been given. If you use our contact form, we collect your name and e-mail address. We also collect any additional, optional information you provide us with. We store your data with the message sent to us, which includes any information about your project or request if provided.&nbsp;</span></p>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:21pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">This data is used to contact you in regards to your initial request. If this results in successful cooperation, we will continue to process your data as we provide you with our services. If not, your data is removed after 2 years. In limited circumstances, we may also use your information for other purposes, where permitted by law. This does not include marketing or advertising purposes. We process data on our own personal servers for the purposes of invoicing.</span></p>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:normal; font-size:18pt; background-color:#ffffff;"><span style="font-family:'Segoe UI';">Protecting Your Personal Data</span></p>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:21pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">We use various technical and organizational security methods, such as encryption, to ensure and maintain the safe storage of your personal data. Your personal data is stored in secured networks and is only accessible by a limited number of people that have been given special, specific rights to access such systems.</span></p>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:normal; font-size:18pt; background-color:#ffffff;"><span style="font-family:'Segoe UI';">Your Personal Data Rights</span></p>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:21pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">We recognize and respect your rights to your personal data. You have the right to request:</span></p>
    <ul type="disc" style="margin:0pt; padding-left:0pt;">
        <li style="margin-top:14pt; margin-left:27.6pt; text-align:justify; line-height:21pt; padding-left:8.4pt; font-family:serif; font-size:10pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">Access to your personal data</span></li>
        <li style="margin-left:27.6pt; text-align:justify; line-height:21pt; padding-left:8.4pt; font-family:serif; font-size:10pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">Amendments to your personal data</span></li>
        <li style="margin-left:27.6pt; text-align:justify; line-height:21pt; padding-left:8.4pt; font-family:serif; font-size:10pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">The complete erasure of your personal data</span></li>
        <li style="margin-left:27.6pt; text-align:justify; line-height:21pt; padding-left:8.4pt; font-family:serif; font-size:10pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">Restrictions on how we process or use your data</span></li>
        <li style="margin-left:27.6pt; margin-bottom:14pt; text-align:justify; line-height:21pt; padding-left:8.4pt; font-family:serif; font-size:10pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">Data portability &ndash; to obtain and reuse your own personal data</span></li>
    </ul>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:21pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">You have the right to object to us processing your personal data in relation to your particular situation. You are also free to opt-out of direct marketing. In situations where we have obtained your consent to process your personal data, you also have the right to withdraw this consent at any time. This will not influence the lawful status of any processing that has occurred before the withdrawal occurred. To enact any of your personal data rights, please contact us at</span><span style="font-family:'Segoe UI'; font-size:12pt;">&nbsp;</span><span style="font-family:'Segoe UI'; font-size:12pt;">info@ucscu.coop. You also have the freedom to lodge a complaint with a supervisory authority. For us, as an Apex for Savings and Credit Societies in Uganda, our supervisory authority is the Cooperative department in the Ministry of Trade, Industry and Cooperatives. You can learn more on the www.mtic.go.ugwebsite.</span></p>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:21pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">&nbsp;</span></p>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:21pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">&nbsp;</span></p>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:normal; font-size:18pt; background-color:#ffffff;"><span style="font-family:'Segoe UI';">Cookies and Pixel Tags</span></p>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:21pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">We receive and record information, which may include personal data, from your browser when you use our website. We use a variety of methods, such as cookies and pixel tags to collect this information, which may include your:</span></p>
    <ul type="disc" style="margin:0pt; padding-left:0pt;">
        <li style="margin-top:14pt; margin-left:27.6pt; text-align:justify; line-height:21pt; padding-left:8.4pt; font-family:serif; font-size:10pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">IP address</span></li>
        <li style="margin-left:27.6pt; text-align:justify; line-height:21pt; padding-left:8.4pt; font-family:serif; font-size:10pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">unique cookie identifier, cookie information and information on whether your device has software to access certain features</span></li>
        <li style="margin-left:27.6pt; text-align:justify; line-height:21pt; padding-left:8.4pt; font-family:serif; font-size:10pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">unique device identifier and device type</span></li>
        <li style="margin-left:27.6pt; text-align:justify; line-height:21pt; padding-left:8.4pt; font-family:serif; font-size:10pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">domain, browser type and language</span></li>
        <li style="margin-left:27.6pt; text-align:justify; line-height:21pt; padding-left:8.4pt; font-family:serif; font-size:10pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">operating system and system settings</span></li>
        <li style="margin-left:27.6pt; text-align:justify; line-height:21pt; padding-left:8.4pt; font-family:serif; font-size:10pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">country and time zone</span></li>
        <li style="margin-left:27.6pt; text-align:justify; line-height:21pt; padding-left:8.4pt; font-family:serif; font-size:10pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">previously visited websites</span></li>
        <li style="margin-left:27.6pt; text-align:justify; line-height:21pt; padding-left:8.4pt; font-family:serif; font-size:10pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">information about your interaction with our website such as click behaviour and indicated preferences</span></li>
        <li style="margin-left:27.6pt; margin-bottom:14pt; text-align:justify; line-height:21pt; padding-left:8.4pt; font-family:serif; font-size:10pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">access times and referring URLs</span></li>
    </ul>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:21pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">Third parties may also collect information via our website through the use of cookies or third-party widgets and plug-ins. These particles collect data directly from your web browser, processing the data under their own privacy policies. We also use cookies and pixel tags to track how visitors use our website and to gain insight into their preferences. Through these, we collect aggregate data about site traffic and user interaction. This helps us identify trends and acquire statistics that can be used to improve the website.</span></p>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:normal; font-size:18pt; background-color:#ffffff;"><span style="font-family:'Segoe UI';">How to manage cookies?</span></p>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:21pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">Your web browser&rsquo;s settings can change your preferences regarding cookie storage. Most browsers also let you review and erase cookies as well. Please be aware, however, that our website will not operate properly without cookies enabled. For more information, we refer you to the help pages from browser manufacturers regarding managing cookies in their specific browsers.</span></p>
    <ul type="disc" style="margin:0pt; padding-left:0pt;">
        <li style="margin-top:14pt; margin-left:27.6pt; text-align:justify; line-height:21pt; padding-left:8.4pt; font-family:serif; font-size:10pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">Google Chrome</span></li>
        <li style="margin-left:27.6pt; text-align:justify; line-height:21pt; padding-left:8.4pt; font-family:serif; font-size:10pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">Internet Explorer</span></li>
        <li style="margin-left:27.6pt; text-align:justify; line-height:21pt; padding-left:8.4pt; font-family:serif; font-size:10pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">Mozilla Firefox</span></li>
        <li style="margin-left:27.6pt; text-align:justify; line-height:21pt; padding-left:8.4pt; font-family:serif; font-size:10pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">domain, browser type and language</span></li>
        <li style="margin-left:27.6pt; text-align:justify; line-height:21pt; padding-left:8.4pt; font-family:serif; font-size:10pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">Safari &ndash; Desktop &amp; Mobile</span></li>
        <li style="margin-left:27.6pt; text-align:justify; line-height:21pt; padding-left:8.4pt; font-family:serif; font-size:10pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">Android Browser</span></li>
        <li style="margin-left:27.6pt; margin-bottom:14pt; text-align:justify; line-height:21pt; padding-left:8.4pt; font-family:serif; font-size:10pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">Opera &ndash; Desktop &amp; Mobile</span></li>
    </ul>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:21pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">For browsers not included here, please refer to the appropriate documentation provided by the manufacturer. If you have any issues or queries regarding the processing of personal data, the use of cookies, or our pixel tags, please contact us at</span><span style="font-family:'Segoe UI'; font-size:12pt;">&nbsp;</span><span style="font-family:'Segoe UI'; font-size:12pt;">info@ucscu.coop. For requests regarding your personal data and privacy complaints, we strive to resolve the issue in an effective and timely manner. CHANGES TO THIS PRIVACY POLICY,UCSCU has the discretion to update this privacy policy at any time. When we do, we will revise the updated date at the bottom of this page. We encourage Users to frequently check this page for any changes to stay informed about how we are helping to protect the personal information we collect. You acknowledge and agree that it is your responsibility to review this privacy policy periodically and become aware of modifications.</span></p>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:normal; font-size:18pt; background-color:#ffffff;"><span style="font-family:'Segoe UI';">Acceptance terms</span></p>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:21pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">By using this Site, you signify your acceptance of this policy and terms of service. If you do not agree to this policy, please do not use our Site. Your continued use of the Site following the posting of changes to this policy will be deemed your acceptance of those changes.</span></p>


    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:normal; font-size:18pt; background-color:#ffffff;"><span style="font-family:'Segoe UI';">Contacting us</span></p>
    <p style="margin-top:0pt; margin-bottom:14pt; text-align:justify; line-height:21pt; background-color:#ffffff;"><span style="font-family:'Segoe UI'; font-size:12pt;">If you have any questions about this Privacy Policy, the practices of this site, or your dealings with this site, please contact us at:</span></p>
    <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; line-height:normal; font-size:12pt; background-color:#ffffff;"><span style="font-family:'Segoe UI';">UGANDA COOPERATIVE SAVINGS AND CREDIT UNION</span></p>
    <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; line-height:normal; font-size:12pt; background-color:#ffffff;"><span style="font-family:'Segoe UI';">10Kms Bombo Road, Plot 239, Maganjo-Wakiso District</span></p>
    <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; line-height:normal; font-size:12pt; background-color:#ffffff;"><span style="font-family:'Segoe UI';">P.O.Box: 6203, Kampala-Uganda</span></p>
    <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; line-height:normal; font-size:12pt; background-color:#ffffff;"><span style="font-family:'Segoe UI';">Tel: +256 414 233 601</span></p>
    <p style="margin-top:0pt; margin-bottom:0pt; text-align:justify; line-height:normal; font-size:12pt; background-color:#ffffff;"><span style="font-family:'Segoe UI';">info@ucscu.coop</span></p>
    <div style="clear:both;">
        <p style="margin-top:0pt; margin-bottom:0pt; text-align:center; line-height:normal; font-size:8pt;"><strong><em>UCSCU-PRIVACY POLICY, info@ucscu.coop</em></strong></p>
    </div>
</div>