<?php
require_once('includes/response.php');
require_once('includes/ReportService.php');
require_once('includes/reports_css.php');
require_once('includes/reports_page_css.php');

$response = new Response();
$ReportService = new ReportService();
$request_data = [];
$request_data['is_trial_balance'] = true;
$request_data['with_income_totals'] = false;
$request_data['with_expenditure_totals'] = false;
$request_data['with_assets_totals'] = false;
$request_data['with_liabilities_totals'] = false;
$request_data['with_capital_totals'] = false;
$request_data['with_suspense_totals'] = false;
if (@$_REQUEST['branch']) {
    $request_data['bid'] = @$_REQUEST['branch'];
    $request_data['bankk'] = '';
    $_REQUEST['bankk'] = '';
} else {
    $request_data['bid'] = '';
}
$request_data = array_merge($request_data, $_REQUEST);
$report_reponse = $ReportService->generateTrialBalance($request_data);
$records = @$report_reponse['data'] ?? [];
$sub_report_reponse = $ReportService->generateTrialBalanceSubAccounts($request_data);
$sub_records = @$sub_report_reponse['data'] ?? [];


$income_accounts = @$records['income'] ?? [];
$income_sub_accounts = @$sub_records['income'] ?? [];
$expenses_accounts = @$records['expenses'] ?? [];
$expenses_sub_accounts = @$sub_records['expenses'] ?? [];
$suspense_accounts = @$records['suspenses'] ?? [];
$suspense_sub_accounts = @$sub_records['suspenses'] ?? [];
$assets_accounts = @$records['assets'] ?? [];
$assets_sub_accounts = @$sub_records['assets'] ?? [];
$liabilites_accounts = @$records['liabilities'] ?? [];
$liabilities_sub_accounts = @$sub_records['liabilities'] ?? [];
$capital_accounts = @$records['capital'] ?? [];
$capital_sub_accounts = @$sub_records['capital'] ?? [];
?>

<?php
require_once('includes/report_header.php');
?>

<section class="report-section">

    <table class="main-header">
        <tr>
            <td> <strong> trial balance </strong></td>
        </tr>
    </table>

    <table>

        <tr>
            <td colspan="2">
                <div>
                    Printed On: <strong> <?= (isset($_REQUEST['transaction_end_date']) && $_REQUEST['transaction_end_date'] != '') ? normal_date($_REQUEST['transaction_end_date']) :  normal_date(date('Y-m-d')) ?> </strong>
                </div>
            </td>
        </tr>


        <?php if (@$_REQUEST['transaction_start_date'] && @$_REQUEST['transaction_end_date']) : ?>
            <tr>
                <td colspan="2">
                    <div>
                        From: <strong> <?= normal_date($_REQUEST['transaction_start_date']) ?> </strong>
                        To: <strong> <?= normal_date($_REQUEST['transaction_end_date']) ?> </strong>
                    </div>
                </td>
            </tr>
        <?php else : ?>
            <tr>
                <td colspan="2">
                    <div>
                        As at: <strong> <?= date('Y-m-d H:i:s') ?> </strong>

                    </div>
                </td>
            </tr>
        <?php endif ?>
        <tr>
            <td colspan="2">
                <div>
                    Generated By: <strong> <?= $user[0]['firstName'] . ' ' . $user[0]['lastName'] . ' - ' . $user[0]['positionTitle']; ?> </strong>

                </div>
            </td>
        </tr>

    </table>

    <table class="report_table" id="trial_bal">
        <thead>
            <tr>
                <th>Account Code</th>
                <th>Account Name</th>
                <th>Debit</th>
                <th>Credit</th>

            </tr>

        </thead>
        <tbody>

            <tr>
                <th>1</th>
                <th colspan="5">ASSETS</th>
            </tr>
            <?php
            $i = 1;

            foreach ($assets_accounts as $record) {
                $ac_bal = 0;
                if (is_null($record['main_account_id']) || $record['subs'] > 0) {

            ?>
                    <tr style="font-weight: bolder;" id="row-<?= $record['account_id'] ?>" data-id="<?= $record['account_id'] ?>">
                        <td> <?= $record['account_code_used'] ?? ''; ?></td>
                        <td> <?= $record['account_name'] ?> </td>

                        <td style="text-align:right;"><a href="report_journal_entries.php?filtered=1&branchId=&transaction_type=&authorized_by_id=&acid=<?= $record['account_id'] ?>&transaction_start_date=&transaction_end_date=" class="text-primary details">
                                <?= number_format(0); ?>
                            </a>
                        </td>
                        <td style="text-align:right;"><a href="report_journal_entries.php?filtered=1&branchId=&transaction_type=&authorized_by_id=&acid=<?= $record['account_id'] ?>&transaction_start_date=&transaction_end_date=" class="text-primary ">

                            </a>
                        </td>


                    </tr>
                    <?php

                }
                foreach ($assets_sub_accounts as $subs) {
                    $link = '';
                    if ($subs['main_account_id'] == $record['account_id'] && $subs['subs'] == 0) {
                        $link = 'report_journal_entries.php?filtered=1&branchId=&transaction_type=&authorized_by_id=&acid=' . $subs['account_id'] . '&transaction_start_date=&transaction_end_date=';

                        if ($subs['lpid'] > 0) {
                            $link = 'report_journal_entries_loans.php?id=' . $subs['lpid'] . '&branch=' . $subs['branchId'] . '&acid=' . $subs['account_id'] . '&transaction_start_date=' . @$_REQUEST['transaction_start_date'] ?? date('Y-m-d') . '&transaction_end_date=' . @$_REQUEST['transaction_end_date'] ?? date('Y-m-d') . '';
                        }

                        if ($subs['is_cash_account'] > 0) {
                            $link = 'teller_till_sheet.php?cash_account=' . $subs['account_id'] . '&from_date=1900-01-01&to_date=' . @$_REQUEST['transaction_end_date'] . '';
                        }

                        if ($subs['bank_account'] > 0) {
                            $link = 'bank_reconciliation_tool.php?cash_account=' . $subs['account_id'] . '&from_date=1900-01-01&to_date=' . @$_REQUEST['transaction_end_date'] . '';
                        }

                        if ($subs['reserve_account'] > 0) {
                            $link = 'reconciliation_tool_all.php?cash_account=' . $subs['account_id'] . '&from_date=1900-01-01&to_date=' . @$_REQUEST['transaction_end_date'] . '';
                        }

                    ?>

                        <tr id="row-<?= $subs['account_id'] ?>" data-id="<?= $subs['account_id'] ?>">
                            <td> <?= $subs['account_code_used'] ?? ''; ?></td>
                            <td> <?= $subs['account_name'] ?> </td>


                            <td style="text-align:right;" class="text-primary"><a href="<?= $link ?>" class="text-primary details">
                                    <?= number_format(0) ?></a>
                            </td>
                            <!-- <td style="text-align:right;"></td> -->
                            <td style="text-align:right;" class="text-primary"><a href="report_journal_entries.php?filtered=1&branchId=&transaction_type=&authorized_by_id=&acid=<?= $subs['account_id'] ?>&transaction_start_date=&transaction_end_date=" class="text-primary"></a>
                            </td>

                        </tr>

            <?php

                    }
                }
            } ?>
            <tr style="text-align:right;">
                <th colspan="2">Total for Assets</th>


                <!-- closing totals -->
                <th><?= number_format(0.00) ?></th>
                <th><?= number_format(0.00) ?></th>
            </tr>
            <tr>
                <th>2</th>
                <th colspan="5">LIABILITIES</th>
            </tr>

            <?php
            $i = 1;

            foreach ($liabilites_accounts as $record) {
                if (is_null($record['main_account_id']) || $record['subs'] > 0) {

            ?>
                    <tr style="font-weight: bolder;" id="row-<?= $record['account_id'] ?>" data-id="<?= $record['account_id'] ?>">
                        <td> <?= $record['account_code_used'] ?? ''; ?></td>
                        <td> <?= $record['account_name'] ?> </td>

                        <td style="text-align:right;" class="text-primary"><a href="report_journal_entries.php?filtered=1&branchId=&transaction_type=&authorized_by_id=&acid=<?= $record['account_id'] ?>&transaction_start_date=&transaction_end_date=" class="text-primary ">
                            </a>
                        </td>
                        <td style="text-align:right;" class="text-primary"><a href="report_journal_entries.php?filtered=1&branchId=&transaction_type=&authorized_by_id=&acid=<?= $record['account_id'] ?>&transaction_start_date=&transaction_end_date=" class="text-primary details">
                                <?= number_format(0.00) ?></a>
                        </td>

                    </tr>
                    <?php

                }

                foreach ($liabilities_sub_accounts as $subs) {
                    if ($subs['main_account_id'] == $record['account_id'] && $subs['subs'] == 0) {

                        $link2 = 'report_journal_entries.php?filtered=1&branchId=&transaction_type=&authorized_by_id=&acid=' . $subs['account_id'] . '&transaction_start_date=&transaction_end_date=';

                        if ($subs['said'] > 0) {
                            $link2 = 'report_savings_per_product.php?filtered=1&branch=' . @$subs['branchId'] . '&said=' . $subs['said'] . '&transaction_type=&authorized_by_id=&acid=' . $subs['account_id'] . '&transaction_start_date=&transaction_end_date=';
                        }

                        if ($subs['is_fixed_acc'] > 0) {
                            $link2 = 'report_journal_fds.php?filtered=1&branch=' . @$subs['branchId'] . '&transaction_type=&authorized_by_id=&acid=' . $subs['account_id'] . '&transaction_start_date=&transaction_end_date=';
                        }





                    ?>

                        <tr id="row-<?= $subs['account_id'] ?>" data-id="<?= $subs['account_id'] ?>">
                            <td> <?= $subs['account_code_used'] ?? ''; ?></td>
                            <td> <?= $subs['account_name'] ?> </td>

                            <td style="text-align:right;" class="text-primary"><a href="" class="text-primary">
                                </a>
                            </td>
                            <td style="text-align:right;" class="text-primary"><a href="<?= $link2 ?>" class="text-primary details">
                                    <?= number_format(0.00) ?></a>
                            </td>

                        </tr>

            <?php

                    }
                }
            } ?>
            <tr style="text-align:right;">


                <th colspan="2">Total for Liabilities</th>

                <!-- closing totals -->
                <th><?= number_format(0.00) ?></th>
                <th><?= number_format(0.00) ?></th>
            </tr>

            <tr>
                <th>3</th>
                <th colspan="5">CAPITAL</th>
            </tr>

            <?php
            $i = 1;

            foreach ($capital_accounts as $record) {
                if (is_null($record['main_account_id']) || $record['subs'] > 0) {

            ?>
                    <tr style="font-weight: bolder;" id="row-<?= $record['account_id'] ?>" data-id="<?= $record['account_id'] ?>">
                        <td> <?= $record['account_code_used'] ?? ''; ?></td>
                        <td> <?= $record['account_name'] ?> </td>


                        <td style="text-align:right;" class="text-primary"><a href="report_journal_entries.php?filtered=1&branchId=&transaction_type=&authorized_by_id=&acid=<?= $record['account_id'] ?>&transaction_start_date=&transaction_end_date=" class="text-primary">
                                <?= number_format(0.00) ?></a>
                        </td>
                        <td style="text-align:right;" class="text-primary"><a href="report_journal_entries.php?filtered=1&branchId=&transaction_type=&authorized_by_id=&acid=<?= $record['account_id'] ?>&transaction_start_date=&transaction_end_date=" class="text-primary details">
                                <?= number_format(0.00) ?></a>
                        </td>

                    </tr>
                    <?php

                }
                foreach ($capital_sub_accounts as $subs) {
                    if ($subs['main_account_id'] == $record['account_id'] && $subs['subs'] == 0) {

                    ?>

                        <tr id="row-<?= $subs['account_id'] ?>" data-id="<?= $subs['account_id'] ?>">
                            <td> <?= $subs['account_code_used'] ?? ''; ?></td>
                            <td> <?= $subs['account_name'] ?> </td>

                            <td style="text-align:right;" class="text-primary"><a href="" class="text-primary">
                                </a>
                            </td>
                            <td style="text-align:right;" class="text-primary"><a href="<?= $subs['is_share_acc'] > 0 ? 'report_journal_shares.php?filtered=1&branch=' . @$subs['branchId'] . '&transaction_type=&authorized_by_id=&acid=' . $subs['account_id'] . '&transaction_start_date=&transaction_end_date=' : 'report_journal_entries.php?filtered=1&branchId=&transaction_type=&authorized_by_id=&acid=' . $subs['account_id'] . '&transaction_start_date=&transaction_end_date=' ?>" class="text-primary details">
                                    <?= number_format(0.00) ?></a>
                            </td>

                        </tr>

            <?php

                    }
                }
            } ?>
            <tr style="text-align:right;">


                <th colspan="2">Total for Capital</th>

                <!-- closing totals -->
                <th><?= number_format(0.00) ?></th>
                <th><?= number_format(0.00) ?></th>
            </tr>

            <tr>
                <th>4</th>
                <th colspan="5">INCOMES</th>
            </tr>
            <?php
            $i = 1;

            foreach ($income_accounts as $income) {


                if (is_null($income['main_account_id']) || $income['subs'] > 0) {




            ?>
                    <tr style="font-weight: bolder;" id="row-<?= $record['account_id'] ?>" data-id="<?= $record['account_id'] ?>">
                        <td> <?= $income['account_code_used'] ?? ''; ?></td>
                        <td> <?= $income['account_name'] ?> </td>

                        <td style="text-align:right;" class="text-primary"><a href="report_journal_entries.php?filtered=1&branchId=&transaction_type=&authorized_by_id=&acid=<?= $income['account_id'] ?>&transaction_start_date=&transaction_end_date=" class="text-primary">
                            </a>
                        </td>
                        <td style="text-align:right;" class="text-primary"><a href="report_journal_entries.php?filtered=1&branchId=&transaction_type=&authorized_by_id=&acid=<?= $income['account_id'] ?>&transaction_start_date=&transaction_end_date=" class="text-primary details">
                                <?= number_format(0.00) ?></a>
                        </td>

                    </tr>
                    <?php

                }

                foreach ($income_sub_accounts as $subs) {
                    if ($subs['main_account_id'] == $income['account_id'] && $subs['subs'] == 0) {

                    ?>

                        <tr id="row-<?= $subs['account_id'] ?>" data-id="<?= $subs['account_id'] ?>">
                            <td> <?= $subs['account_code_used'] ?? ''; ?></td>
                            <td> <?= $subs['account_name'] ?> </td>

                            <td style="text-align:right;" class="text-primary"><a href="report_journal_entries.php?filtered=1&branchId=&transaction_type=&authorized_by_id=&acid=<?= $subs['account_id'] ?>&transaction_start_date=&transaction_end_date=" class="text-primary">
                                </a>
                            </td>
                            <td style="text-align:right;" class="text-primary"><a href="<?= ($subs['lpid'] > 0 && (!str_contains(@$subs['account_name'], 'Penalty'))) ? 'report_journal_entries_loans.php?id=' . $subs['lpid'] . '&branch=' . $subs['branchId'] . '&acid=' . $subs['account_id'] . '&transaction_start_date=&transaction_end_date=' : 'report_journal_entries.php?filtered=1&branchId=&transaction_type=&authorized_by_id=&acid=' . $subs['account_id'] . '&transaction_start_date=&transaction_end_date='  ?>" class="text-primary details">
                                    <?= number_format(0.00) ?></a>
                            </td>

                        </tr>

            <?php

                    }
                }
            } ?>

            <tr style="text-align:right;">
                <th colspan="2">Total for Income</th>

                <!-- closing totals -->
                <th><?= number_format(0.00) ?></th>
                <th><?= number_format(0.00) ?></th>
            </tr>


            <tr>
                <th>5</th>
                <th colspan="5">EXPENSES</th>
            </tr>

            <?php
            $i = 1;

            foreach ($expenses_accounts as $expense) {
                if (is_null($expense['main_account_id']) || $expense['subs'] > 0) {
            ?>
                    <tr style="font-weight: bolder;" id="row-<?= $record['account_id'] ?>" data-id="<?= $record['account_id'] ?>">
                        <td> <?= $expense['account_code_used'] ?? ''; ?></td>
                        <td> <?= $expense['account_name'] ?> </td>

                        <td style="text-align:right;" class="text-primary details">
                            <?= number_format(0.00) ?>
                        </td>
                        <td style="text-align:right;" class="text-primary">
                            <?= number_format(0.00) ?>
                        </td>

                    </tr>
                    <?php

                }
                foreach ($expenses_sub_accounts as $subs) {
                    if ($subs['main_account_id'] == $expense['account_id'] && $subs['subs'] == 0) { ?>

                        <tr id="row-<?= $subs['account_id'] ?>" data-id="<?= $subs['account_id'] ?>">
                            <td> <?= $subs['account_code_used'] ?? ''; ?></td>
                            <td> <?= $subs['account_name'] ?> </td>


                            <td style="text-align:right;" class="text-primary details">
                                <?= number_format(0.00) ?>
                            </td>
                            <td style="text-align:right;" class="text-primary">
                                <?= number_format(0.00) ?>
                            </td>

                        </tr>

            <?php

                    }
                }
            } ?>
            <tr style="text-align:right;">
                <th colspan="2">Total for Expenses</th>

                <!-- closing totals -->
                <th><?= number_format(0.00) ?></th>
                <th><?= number_format(0.00) ?></th>
            </tr>


            <tr>
                <th>6</th>
                <th colspan="7">SUSPENSE AND ERROR ACCOUNTS</th>
            </tr>

            <?php
            $i = 1;

            foreach ($suspense_accounts as $suspense) {
                if (is_null($suspense['main_account_id']) || $suspense['subs'] > 0) {
            ?>
                    <tr style="font-weight: bolder;" id="row-<?= $suspense['account_id'] ?>" data-id="<?= $suspense['account_id'] ?>">
                        <td> <?= $suspense['account_code_used'] ?? ''; ?></td>
                        <td> <?= $suspense['account_name'] ?> </td>

                        <td style="text-align:right;" class="text-primary details">
                            <?= number_format(0) ?>
                        </td>
                        <td style="text-align:right;" class="text-primary">
                            <?= number_format(0.00) ?>
                        </td>

                    </tr>
                    <?php

                }
                foreach ($suspense_sub_accounts as $subs) {
                    if ($subs['main_account_id'] == $suspense['account_id'] && $subs['subs'] == 0) { ?>

                        <tr id="row-<?= $subs['account_id'] ?>" data-id="<?= $subs['account_id'] ?>">
                            <td> <?= $subs['account_code_used'] ?? ''; ?></td>
                            <td> <?= $subs['account_name'] ?> </td>


                            <td style="text-align:right;" class="text-primary details">
                                <?= number_format(0) ?>
                            </td>
                            <td style="text-align:right;" class="text-primary">
                                <?= number_format(0.00) ?>
                            </td>

                        </tr>

            <?php
                    }
                }
            } ?>
            <tr style="text-align:right;">
                <th colspan="2">Total for Suspenses</th>

                <!-- closing totals -->
                <th><?= number_format(0.00) ?></th>
                <th><?= number_format(0.00) ?></th>
            </tr>




            <tr>

                <th colspan="2">GRAND TOTALS</th>

                <!-- closing totals -->
                <th><?= number_format(0.00) ?></th>
                <th><?= number_format(0.00) ?></th>


            </tr>

        </tbody>

    </table>


</section>
<?php
include('includes/bottom_scripts.php');
?>
<script>
    $(document).ready(function() {
        $('tr[data-id]').each(function() {
            var rowId = $(this).data('id');
            $.ajax({
                url: 'https://app.ucscucbs.net/backend/api/Bank/fetchTrialValues.php?start=<?= @$_REQUEST['transaction_start_date'] ?>&end=<?= @$_REQUEST['transaction_end_date'] ?>&branch=<?= @$_REQUEST['branch'] ?>&bankk=<?= @$_REQUEST['bankk'] ?>',
                method: 'GET',
                data: {
                    id: rowId
                },
                success: function(response) {
                    // Assuming response is JSON with a 'details' field
                    $('#row-' + rowId + ' .details').text(response.details);
                },
                error: function() {
                    $('#row-' + rowId + ' .details').text('0');
                }
            });
        });
    });
</script>